dvrk/PSM1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20  

  # Position Controllers ---------------------------------------
  joint_traj_controller:
    type: "position_controllers/JointTrajectoryController"
    #These should always reflect the joint names given in cwru_davinci_geometry_models/model
    joints:
        - PSM1/outer_yaw
        - PSM1/outer_pitch
        - PSM1/outer_insertion
        - PSM1/outer_roll
        - PSM1/outer_wrist_pitch
        - PSM1/outer_wrist_yaw
        - PSM1/jaw
    gains:
        PSM1/outer_yaw: {p: 0, i: 0, d: 0}
        PSM1/outer_pitch: {p: 0, i: 0, d: 0}
        PSM1/outer_insertion: {p: 0, i: 0, d: 0}
        PSM1/outer_roll: {p: 0, i: 0, d: 0}
        PSM1/outer_wrist_pitch: {p: 0, i: 0, d: 0}
        PSM1/outer_wrist_yaw: {p: 0, i: 0, d: 0}
        PSM1/jaw: {p: 0, i: 0, d: 0}
    allow_partial_joints_goal: true
        

# dvrk/PSM1:
#   # Publish all joint states -----------------------------------
#   joint_state_controller:
#     type: joint_state_controller/JointStateController
#     publish_rate: 20  

#   # Position Controllers ---------------------------------------
#   joint_traj_controller:
#     type: "position_controllers/JointTrajectoryController"
#     #These should always reflect the joint names given in cwru_davinci_geometry_models/model
#     joints:
#         - outer_yaw
#         - outer_pitch
#         - outer_insertion
#         - outer_roll
#         - outer_wrist_pitch
#         - outer_wrist_yaw
#         - jaw
#     gains:
#         outer_yaw: {p: 0, i: 0, d: 0}
#         outer_pitch: {p: 0, i: 0, d: 0}
#         outer_insertion: {p: 0, i: 0, d: 0}
#         outer_roll: {p: 0, i: 0, d: 0}
#         outer_wrist_pitch: {p: 0, i: 0, d: 0}
#         outer_wrist_yaw: {p: 0, i: 0, d: 0}
#         jaw: {p: 0, i: 0, d: 0}
#     allow_partial_joints_goal: true

#  joint_group_controller:
#    type: "effort_controllers/JointGroupPositionController"
#    joints:
#        - outer_yaw
#    gains:
#        outer_yaw: {p: 100.0, i: 0.5, d: 10.0}

        
#  joint_group_controller:
#    type: "effort_controllers/JointGroupPositionController"
#    joints:
#        - outer_yaw
#    gains:
#        outer_yaw: {p: 100.0, i: 0.5, d: 10.0}
